const yesNo = [
  { value: '1', label: 'Yes' },
  { value: '0', label: 'No' },
];

const adPlacements = [
  { value: 'banner', label: 'Banner' },
  { value: 'sidebar-left', label: 'Sidebar (Left)' },
  { value: 'sidebar-right', label: 'Sidebar (Right)' },
  { value: 'footer', label: 'Footer' },
  { value: 'sidebar', label: 'Sidebar (Legacy)' },
];

const siteDisplayLocations = [
  { value: 'header', label: 'Header' },
  { value: 'footer', label: 'Footer' },
];

const donationDisplayLocations = [
  { value: 'footer', label: 'Footer / Sidebar Widget' },
  { value: 'donation_page', label: 'Donate Page' },
];

const staticPageRoutes = [
  { value: '', label: 'None (standalone page)' },
  { value: 'home', label: 'Home' },
  { value: 'donate', label: 'Donate' },
  { value: 'contact', label: 'Contact' },
  { value: 'bible', label: 'Holy Bible' },
  { value: 'mass-guide', label: 'Mass Guide' },
  { value: 'fiesta-calendar', label: 'Fiesta Calendar' },
  { value: 'novenas', label: 'Novenas' },
  { value: 'prayers', label: 'Prayers' },
  { value: 'ai-advice', label: 'AI Advice' },
];

const pageBannerRoutes = [
  { value: 'home', label: 'Home' },
  { value: 'bible', label: 'Holy Bible' },
  { value: 'bible-chapter', label: 'Bible Chapter' },
  { value: 'mass-guide', label: 'Mass Guide' },
  { value: 'mass-guide-date', label: 'Mass Guide (Date)' },
  { value: 'fiesta-calendar', label: 'Fiesta Calendar' },
  { value: 'novenas', label: 'Novenas' },
  { value: 'novena-detail', label: 'Novena Detail' },
  { value: 'prayers', label: 'Prayers' },
  { value: 'prayer-detail', label: 'Prayer Detail' },
  { value: 'ai-advice', label: 'AI Advice' },
  { value: 'about', label: 'About Us' },
  { value: 'privacy', label: 'Privacy Policy' },
  { value: 'terms', label: 'Terms & Conditions' },
  { value: 'contact', label: 'Contact' },
  { value: 'donate', label: 'Donate' },
];

const fiestaCategories = [
  { value: 'christ', label: 'Jesus Christ' },
  { value: 'father', label: 'God the Father / Trinity' },
  { value: 'mary', label: 'Mother Mary' },
  { value: 'saint', label: 'Saints' },
  { value: 'angel', label: 'Angels' },
];

const fiestaRanks = [
  { value: 'solemnity', label: 'Solemnity' },
  { value: 'feast', label: 'Feast' },
  { value: 'memorial', label: 'Memorial' },
  { value: 'optional_memorial', label: 'Optional Memorial' },
];

const fiestaMovableRules = [
  { value: 'ash_wednesday', label: 'Ash Wednesday' },
  { value: 'palm_sunday', label: 'Palm Sunday' },
  { value: 'holy_thursday', label: 'Holy Thursday' },
  { value: 'good_friday', label: 'Good Friday' },
  { value: 'holy_saturday', label: 'Holy Saturday' },
  { value: 'easter_sunday', label: 'Easter Sunday' },
  { value: 'divine_mercy_sunday', label: 'Divine Mercy Sunday' },
  { value: 'ascension', label: 'Ascension' },
  { value: 'pentecost', label: 'Pentecost' },
  { value: 'trinity_sunday', label: 'Trinity Sunday' },
  { value: 'corpus_christi', label: 'Corpus Christi' },
  { value: 'sacred_heart', label: 'Sacred Heart' },
  { value: 'christ_the_king', label: 'Christ the King' },
];

export const resourceConfigs = {
  'bible-versions': {
    key: 'bible-versions',
    title: 'Bible Versions',
    titleSingular: 'Bible Version',
    endpoint: '/bible-versions',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'abbreviation', label: 'Abbreviation' },
      { key: 'language', label: 'Language' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
    ],
    filters: [
      { key: 'is_active', label: 'Active', options: yesNo },
      { key: 'language', label: 'Language', options: [] },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true, col: 'col-md-6' },
      { key: 'abbreviation', label: 'Abbreviation', required: true, col: 'col-md-6' },
      { key: 'language', label: 'Language', col: 'col-md-6' },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-6' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  'bible-books': {
    key: 'bible-books',
    title: 'Bible Books',
    titleSingular: 'Bible Book',
    endpoint: '/bible-books',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'abbreviation', label: 'Abbr.' },
      { key: 'testament', label: 'Testament' },
      { key: 'book_order', label: 'Order' },
      { key: 'chapter_count', label: 'Chapters' },
      { key: 'version', label: 'Version', accessor: (r) => r.version?.abbreviation || '—' },
    ],
    filters: [
      { key: 'bible_version_id', label: 'Version', options: [] },
      {
        key: 'testament',
        label: 'Testament',
        options: [
          { value: 'old', label: 'Old' },
          { value: 'new', label: 'New' },
        ],
      },
    ],
    formFields: [
      {
        key: 'bible_version_id',
        label: 'Version',
        type: 'select',
        required: true,
        col: 'col-md-6',
        relation: { endpoint: '/bible-versions', label: 'name' },
      },
      { key: 'name', label: 'Name', required: true, col: 'col-md-6' },
      { key: 'abbreviation', label: 'Abbreviation', col: 'col-md-4' },
      {
        key: 'testament',
        label: 'Testament',
        type: 'select',
        required: true,
        col: 'col-md-4',
        options: [
          { value: 'old', label: 'Old Testament' },
          { value: 'new', label: 'New Testament' },
        ],
      },
      { key: 'book_order', label: 'Book Order', type: 'number', required: true, col: 'col-md-4' },
      { key: 'chapter_count', label: 'Chapter Count', type: 'number', required: true, col: 'col-md-6' },
    ],
  },
  'bible-chapters': {
    key: 'bible-chapters',
    title: 'Bible Chapters',
    titleSingular: 'Bible Chapter',
    endpoint: '/bible-chapters',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'chapter_number', label: 'Chapter' },
      { key: 'verse_count', label: 'Verses' },
      { key: 'book', label: 'Book', accessor: (r) => r.book?.name || '—' },
    ],
    filters: [{ key: 'bible_book_id', label: 'Book', options: [] }],
    formFields: [
      {
        key: 'bible_book_id',
        label: 'Book',
        type: 'select',
        required: true,
        relation: { endpoint: '/bible-books', label: 'name' },
      },
      { key: 'chapter_number', label: 'Chapter Number', type: 'number', required: true, col: 'col-md-6' },
      { key: 'verse_count', label: 'Verse Count', type: 'number', col: 'col-md-6' },
    ],
  },
  'bible-verses': {
    key: 'bible-verses',
    title: 'Bible Verses',
    titleSingular: 'Bible Verse',
    endpoint: '/bible-verses',
    formSize: 'xl',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'verse_number', label: 'Verse' },
      { key: 'chapter', label: 'Chapter', accessor: (r) => r.chapter?.chapter_number || '—' },
      { key: 'text', label: 'Text', accessor: (r) => (r.text || '').slice(0, 80) + (r.text?.length > 80 ? '…' : '') },
    ],
    filters: [{
      key: 'bible_chapter_id',
      label: 'Chapter',
      relation: {
        endpoint: '/bible-chapters',
        perPage: 200,
        sort: 'chapter_number',
        direction: 'asc',
        label: (item) => `${item.book?.name || 'Book'} ${item.chapter_number}`,
      },
    }],
    formFields: [
      {
        key: '_bible_book_id',
        label: 'Book',
        type: 'select',
        required: true,
        virtual: true,
        col: 'col-md-6',
        help: 'Select the Bible book first, then choose the chapter.',
        relation: {
          endpoint: '/bible-books',
          perPage: 200,
          sort: 'book_order',
          direction: 'asc',
          label: (item) => `${item.name} (${item.version?.abbreviation || 'Bible'})`,
        },
      },
      {
        key: 'bible_chapter_id',
        label: 'Chapter',
        type: 'select',
        required: true,
        col: 'col-md-6',
        dependsOn: '_bible_book_id',
        relation: {
          endpoint: '/bible-chapters',
          paramsFrom: '_bible_book_id',
          paramKey: 'bible_book_id',
          perPage: 200,
          sort: 'chapter_number',
          direction: 'asc',
          label: (item) => `Chapter ${item.chapter_number}`,
        },
      },
      { key: 'verse_number', label: 'Verse Number', type: 'number', required: true, col: 'col-md-4' },
      { key: 'text', label: 'Text', type: 'textarea', required: true },
    ],
  },
  'mass-guides': {
    key: 'mass-guides',
    title: 'Mass Guides',
    titleSingular: 'Mass Guide',
    endpoint: '/mass-guides',
    formSize: 'xl',
    columns: [
      { key: 'liturgical_date', label: 'Date', format: 'date' },
      { key: 'feast_name', label: 'Feast' },
      { key: 'liturgical_season', label: 'Season' },
      { key: 'gospel_reference', label: 'Gospel Ref.' },
    ],
    filters: [{ key: 'liturgical_season', label: 'Season', options: [] }],
    formFields: [
      { key: 'liturgical_date', label: 'Liturgical Date', type: 'date', required: true, col: 'col-md-4' },
      { key: 'liturgical_year', label: 'Liturgical Year', type: 'number', col: 'col-md-4' },
      { key: 'liturgical_color', label: 'Color', col: 'col-md-4' },
      { key: 'liturgical_season', label: 'Season', col: 'col-md-6' },
      { key: 'feast_name', label: 'Feast Name', col: 'col-md-6' },
      { key: 'first_reading_reference', label: '1st Reading Ref.', col: 'col-md-6' },
      { key: 'first_reading_text', label: '1st Reading Text', type: 'textarea' },
      { key: 'second_reading_reference', label: '2nd Reading Ref.', col: 'col-md-6' },
      { key: 'second_reading_text', label: '2nd Reading Text', type: 'textarea' },
      { key: 'responsorial_psalm_reference', label: 'Psalm Ref.', col: 'col-md-6' },
      { key: 'responsorial_psalm_text', label: 'Psalm Text', type: 'textarea' },
      { key: 'alleluia_reference', label: 'Alleluia Ref.', col: 'col-md-6' },
      { key: 'alleluia_text', label: 'Alleluia Text', type: 'textarea' },
      { key: 'gospel_reference', label: 'Gospel Ref.', col: 'col-md-6' },
      { key: 'gospel_text', label: 'Gospel Text', type: 'textarea' },
    ],
  },
  fiestas: {
    key: 'fiestas',
    title: 'Fiesta Calendar',
    titleSingular: 'Fiesta',
    endpoint: '/fiestas',
    formSize: 'lg',
    columns: [
      { key: 'title', label: 'Title' },
      {
        key: 'schedule',
        label: 'Date',
        accessor: (row) => (row.is_movable ? `Movable (${row.movable_rule || '—'})` : `${row.month}/${row.day}`),
      },
      {
        key: 'category',
        label: 'Category',
        accessor: (row) => fiestaCategories.find((item) => item.value === row.category)?.label || row.category,
      },
      { key: 'liturgical_rank', label: 'Rank' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
    ],
    filters: [
      { key: 'category', label: 'Category', options: fiestaCategories },
      { key: 'liturgical_rank', label: 'Rank', options: fiestaRanks },
      { key: 'is_movable', label: 'Movable', options: yesNo },
      { key: 'is_active', label: 'Active', options: yesNo },
      {
        key: 'month',
        label: 'Month',
        options: [
          { value: '1', label: 'January' },
          { value: '2', label: 'February' },
          { value: '3', label: 'March' },
          { value: '4', label: 'April' },
          { value: '5', label: 'May' },
          { value: '6', label: 'June' },
          { value: '7', label: 'July' },
          { value: '8', label: 'August' },
          { value: '9', label: 'September' },
          { value: '10', label: 'October' },
          { value: '11', label: 'November' },
          { value: '12', label: 'December' },
        ],
      },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true, col: 'col-md-8' },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        required: true,
        col: 'col-md-4',
        options: fiestaCategories,
      },
      {
        key: 'liturgical_rank',
        label: 'Liturgical Rank',
        type: 'select',
        col: 'col-md-4',
        options: fiestaRanks,
      },
      { key: 'honoree_name', label: 'Honoree', col: 'col-md-4' },
      { key: 'sort_order', label: 'Sort Order', type: 'number', col: 'col-md-4' },
      { key: 'is_movable', label: 'Movable Feast', type: 'boolean', col: 'col-md-4' },
      { key: 'feast_date', label: 'Feast Date', type: 'date', col: 'col-md-4' },
      {
        key: 'movable_rule',
        label: 'Movable Rule',
        type: 'select',
        col: 'col-md-4',
        dependsOn: 'is_movable',
        options: fiestaMovableRules,
      },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-4' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  novenas: {
    key: 'novenas',
    title: 'Novenas',
    titleSingular: 'Novena',
    endpoint: '/novenas',
    formSize: 'xl',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'slug', label: 'Slug' },
      { key: 'category', label: 'Category' },
      { key: 'duration_days', label: 'Days' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
      { key: 'visit_count', label: 'Visits' },
    ],
    filters: [
      {
        key: 'category',
        label: 'Category',
        options: [
          { value: 'regular', label: 'Regular' },
          { value: 'common', label: 'Common' },
        ],
      },
      { key: 'is_active', label: 'Active', options: yesNo },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true, col: 'col-md-8' },
      { key: 'slug', label: 'Slug', col: 'col-md-4' },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        col: 'col-md-4',
        options: [
          { value: 'regular', label: 'Regular' },
          { value: 'common', label: 'Common' },
        ],
      },
      { key: 'patron_saint', label: 'Patron Saint', col: 'col-md-4' },
      { key: 'duration_days', label: 'Duration (days)', type: 'number', col: 'col-md-4' },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-4' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'opening_prayer', label: 'Opening Prayer', type: 'textarea' },
      { key: 'closing_prayer', label: 'Closing Prayer', type: 'textarea' },
    ],
  },
  prayers: {
    key: 'prayers',
    title: 'Prayers',
    titleSingular: 'Prayer',
    endpoint: '/prayers',
    formSize: 'lg',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'slug', label: 'Slug' },
      { key: 'category', label: 'Category' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
      { key: 'visit_count', label: 'Visits' },
    ],
    filters: [
      {
        key: 'category',
        label: 'Category',
        options: [
          { value: 'regular', label: 'Regular' },
          { value: 'common', label: 'Common' },
          { value: 'rosary', label: 'Rosary' },
          { value: 'liturgy', label: 'Liturgy' },
          { value: 'other', label: 'Other' },
        ],
      },
      { key: 'is_active', label: 'Active', options: yesNo },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true, col: 'col-md-8' },
      { key: 'slug', label: 'Slug', col: 'col-md-4' },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        col: 'col-md-6',
        options: [
          { value: 'regular', label: 'Regular' },
          { value: 'common', label: 'Common' },
          { value: 'rosary', label: 'Rosary' },
          { value: 'liturgy', label: 'Liturgy' },
          { value: 'other', label: 'Other' },
        ],
      },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-6' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'content', label: 'Content', type: 'textarea', required: true },
    ],
  },
  proverbs: {
    key: 'proverbs',
    title: 'Proverbs',
    titleSingular: 'Proverb',
    endpoint: '/proverbs',
    columns: [
      { key: 'reference', label: 'Reference' },
      { key: 'text', label: 'Text', accessor: (r) => (r.text || '').slice(0, 100) },
      { key: 'bible_version', label: 'Version' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
      { key: 'visit_count', label: 'Visits' },
    ],
    filters: [{ key: 'is_active', label: 'Active', options: yesNo }],
    formFields: [
      { key: 'reference', label: 'Reference', col: 'col-md-4' },
      { key: 'bible_version', label: 'Bible Version', col: 'col-md-4' },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-4' },
      { key: 'text', label: 'Text', type: 'textarea', required: true },
    ],
  },
  'daily-psalms': {
    key: 'daily-psalms',
    title: 'Daily Psalms',
    titleSingular: 'Daily Psalm',
    endpoint: '/daily-psalms',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'psalm_number', label: 'Psalm #' },
      { key: 'reference', label: 'Reference' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
      { key: 'visit_count', label: 'Visits' },
    ],
    filters: [{ key: 'is_active', label: 'Active', options: yesNo }],
    formFields: [
      { key: 'title', label: 'Title', required: true, col: 'col-md-6' },
      { key: 'psalm_number', label: 'Psalm Number', col: 'col-md-3' },
      { key: 'reference', label: 'Reference', col: 'col-md-3' },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-4' },
      { key: 'text', label: 'Text', type: 'textarea', required: true },
    ],
  },
  advertisements: {
    key: 'advertisements',
    title: 'Advertisements',
    titleSingular: 'Advertisement',
    endpoint: '/advertisements',
    formSize: 'lg',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type' },
      { key: 'amount', label: 'Amount' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
      { key: 'impression_count', label: 'Impressions' },
      { key: 'click_count', label: 'Clicks' },
    ],
    filters: [
      {
        key: 'type',
        label: 'Type',
        options: [
          { value: 'embed', label: 'Embed' },
          { value: 'manual', label: 'Manual' },
        ],
      },
      { key: 'is_active', label: 'Active', options: yesNo },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true, col: 'col-md-6' },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        col: 'col-md-6',
        options: [
          { value: 'embed', label: 'Embed' },
          { value: 'manual', label: 'Manual' },
        ],
      },
      { key: 'url', label: 'URL', col: 'col-md-6' },
      { key: 'image_path', label: 'Image Path', col: 'col-md-6' },
      { key: 'amount', label: 'Amount', type: 'number', step: '0.01', col: 'col-md-4' },
      { key: 'start_date', label: 'Start Date', type: 'date', col: 'col-md-4' },
      { key: 'end_date', label: 'End Date', type: 'date', col: 'col-md-4' },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-4' },
      { key: 'placements', label: 'Placements', type: 'multiselect', options: adPlacements, col: 'col-md-6' },
      { key: 'embed_script', label: 'Embed Script', type: 'textarea', plainText: true },
    ],
  },
  'ad-invoices': {
    key: 'ad-invoices',
    title: 'Ad Invoices',
    titleSingular: 'Ad Invoice',
    endpoint: '/ad-invoices',
    columns: [
      { key: 'invoice_number', label: 'Invoice #' },
      { key: 'client_name', label: 'Client' },
      { key: 'amount', label: 'Amount' },
      { key: 'status', label: 'Status' },
      { key: 'invoice_date', label: 'Invoice Date', format: 'date' },
      { key: 'advertisement', label: 'Ad', accessor: (r) => r.advertisement?.name || '—' },
    ],
    filters: [
      {
        key: 'status',
        label: 'Status',
        options: [
          { value: 'draft', label: 'Draft' },
          { value: 'sent', label: 'Sent' },
          { value: 'paid', label: 'Paid' },
          { value: 'cancelled', label: 'Cancelled' },
        ],
      },
    ],
    formFields: [
      {
        key: 'advertisement_id',
        label: 'Advertisement',
        type: 'select',
        required: true,
        relation: { endpoint: '/advertisements', label: 'name' },
      },
      { key: 'invoice_number', label: 'Invoice Number', required: true, col: 'col-md-6' },
      { key: 'client_name', label: 'Client Name', col: 'col-md-6' },
      { key: 'client_email', label: 'Client Email', type: 'email', col: 'col-md-6' },
      { key: 'amount', label: 'Amount', type: 'number', step: '0.01', col: 'col-md-6' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        col: 'col-md-4',
        options: [
          { value: 'draft', label: 'Draft' },
          { value: 'sent', label: 'Sent' },
          { value: 'paid', label: 'Paid' },
          { value: 'cancelled', label: 'Cancelled' },
        ],
      },
      { key: 'invoice_date', label: 'Invoice Date', type: 'date', col: 'col-md-4' },
      { key: 'due_date', label: 'Due Date', type: 'date', col: 'col-md-4' },
      { key: 'paid_date', label: 'Paid Date', type: 'date', col: 'col-md-4' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  'social-media': {
    key: 'social-media',
    title: 'Social Media',
    titleSingular: 'Social Media Setting',
    endpoint: '/social-media-settings',
    columns: [
      { key: 'platform', label: 'Platform' },
      { key: 'handle', label: 'Handle' },
      { key: 'url', label: 'URL' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
    ],
    filters: [{ key: 'is_active', label: 'Active', options: yesNo }],
    formFields: [
      { key: 'platform', label: 'Platform', required: true, col: 'col-md-4' },
      { key: 'handle', label: 'Handle', col: 'col-md-4' },
      { key: 'url', label: 'URL', col: 'col-md-4' },
      { key: 'show_share_buttons', label: 'Show Share Buttons', type: 'boolean', col: 'col-md-4' },
      { key: 'show_follow_links', label: 'Show Follow Links', type: 'boolean', col: 'col-md-4' },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-4' },
      { key: 'display_locations', label: 'Display Locations', type: 'multiselect', options: siteDisplayLocations, col: 'col-md-6' },
    ],
  },
  'system-settings': {
    key: 'system-settings',
    title: 'System Settings',
    titleSingular: 'System Setting',
    endpoint: '/system-settings',
    softDeletes: false,
    columns: [
      { key: 'key', label: 'Key' },
      { key: 'value', label: 'Value' },
      { key: 'group', label: 'Group' },
    ],
    filters: [{ key: 'group', label: 'Group', options: [] }],
    formFields: [
      { key: 'key', label: 'Key', required: true, col: 'col-md-4' },
      { key: 'group', label: 'Group', col: 'col-md-4' },
      { key: 'value', label: 'Value', type: 'textarea', required: true },
    ],
  },
  'page-banners': {
    key: 'page-banners',
    title: 'Page Banners',
    titleSingular: 'Page Banner',
    endpoint: '/page-banners',
    canCreate: false,
    canDelete: false,
    quickToggleField: 'is_active',
    columns: [
      { key: 'label', label: 'Page' },
      { key: 'route_name', label: 'Route' },
      { key: 'image_path', label: 'Banner Image' },
      { key: 'overlay_opacity', label: 'Overlay' },
      { key: 'is_active', label: 'Active', format: 'boolean' },
    ],
    filters: [{ key: 'is_active', label: 'Active', options: yesNo }],
    formFields: [
      {
        key: 'route_name',
        label: 'Page Route',
        type: 'select',
        required: true,
        disableOnEdit: true,
        col: 'col-md-6',
        options: pageBannerRoutes,
      },
      { key: 'label', label: 'Label', required: true, col: 'col-md-6' },
      {
        key: 'image_path',
        label: 'Banner Image',
        type: 'banner-image',
        fileKey: 'banner_image',
        col: 'col-12',
        help: 'Recommended size 1920 × 480 px. Use the cropper after selecting an image.',
      },
      {
        key: 'overlay_opacity',
        label: 'Overlay Opacity',
        type: 'number',
        step: '0.05',
        col: 'col-md-4',
        help: 'Dark overlay over the image (0.2–0.9) so title and verse text stay readable.',
      },
      { key: 'sort_order', label: 'Sort Order', type: 'number', col: 'col-md-4' },
      { key: 'is_active', label: 'Active', type: 'boolean', col: 'col-md-4' },
    ],
  },
  'donation-settings': {
    key: 'donation-settings',
    title: 'Donation Settings',
    titleSingular: 'Donation Setting',
    endpoint: '/donation-settings',
    quickToggleField: 'is_active',
    columns: [
      { key: 'label', label: 'Label' },
      { key: 'type', label: 'Type' },
      { key: 'sort_order', label: 'Order' },
      { key: 'is_active', label: 'Enabled', format: 'boolean' },
    ],
    filters: [
      {
        key: 'type',
        label: 'Type',
        options: [
          { value: 'bank', label: 'Bank' },
          { value: 'paypal', label: 'PayPal' },
          { value: 'ewallet', label: 'E-Wallet' },
        ],
      },
      { key: 'is_active', label: 'Active', options: yesNo },
    ],
    formFields: [
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        col: 'col-md-4',
        options: [
          { value: 'bank', label: 'Bank' },
          { value: 'paypal', label: 'PayPal' },
          { value: 'ewallet', label: 'E-Wallet' },
        ],
      },
      { key: 'label', label: 'Label', required: true, col: 'col-md-4' },
      { key: 'sort_order', label: 'Sort Order', type: 'number', col: 'col-md-4' },
      { key: 'account_name', label: 'Account Name', col: 'col-md-6' },
      { key: 'account_number', label: 'Account Number', col: 'col-md-6' },
      { key: 'bank_name', label: 'Bank Name', col: 'col-md-6' },
      { key: 'paypal_email', label: 'PayPal Email', type: 'email', col: 'col-md-6' },
      { key: 'ewallet_provider', label: 'E-Wallet Provider', col: 'col-md-6' },
      { key: 'ewallet_number', label: 'E-Wallet Number', col: 'col-md-6' },
      {
        key: 'qr_code_path',
        label: 'QR Code Image',
        type: 'image',
        fileKey: 'qr_code',
        col: 'col-md-6',
        help: 'Upload a QR code image for scan-to-pay (GCash, bank, etc.).',
      },
      { key: 'is_active', label: 'Enabled', type: 'boolean', col: 'col-md-4' },
      { key: 'display_locations', label: 'Display Locations', type: 'multiselect', options: donationDisplayLocations, col: 'col-md-6' },
      { key: 'instructions', label: 'Instructions', type: 'textarea' },
    ],
  },
  'static-pages': {
    key: 'static-pages',
    title: 'Static Pages',
    titleSingular: 'Static Page',
    endpoint: '/static-pages',
    formSize: 'xl',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'slug', label: 'Slug' },
      { key: 'page_route', label: 'Linked Page' },
      { key: 'is_published', label: 'Published', format: 'boolean' },
    ],
    filters: [
      { key: 'is_published', label: 'Published', options: yesNo },
      { key: 'page_route', label: 'Linked Page', options: staticPageRoutes.filter((option) => option.value) },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true, col: 'col-md-6' },
      { key: 'slug', label: 'Slug', required: true, col: 'col-md-6', help: 'URL slug for standalone pages (e.g. about-us).' },
      {
        key: 'page_route',
        label: 'Linked Site Page',
        type: 'select',
        col: 'col-md-6',
        options: staticPageRoutes,
        help: 'Optional. Links this content to a site page header (Donate, Contact, Home, etc.). Leave empty for full standalone pages like About Us.',
      },
      { key: 'is_published', label: 'Published', type: 'boolean', col: 'col-md-6' },
      { key: 'meta_description', label: 'Meta Description', col: 'col-12' },
      {
        key: 'content',
        label: 'Page Content',
        type: 'page-builder',
        col: 'col-12',
        help: 'Intro text and blocks shown on the page. For linked pages, this appears above dynamic content (donation options, contact form, listings, etc.).',
      },
    ],
  },
  'contact-messages': {
    key: 'contact-messages',
    title: 'Contact Messages',
    titleSingular: 'Contact Message',
    endpoint: '/contact-messages',
    canCreate: false,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'subject', label: 'Subject' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Received', format: 'datetime' },
    ],
    filters: [
      {
        key: 'status',
        label: 'Status',
        options: [
          { value: 'new', label: 'New' },
          { value: 'read', label: 'Read' },
          { value: 'replied', label: 'Replied' },
          { value: 'archived', label: 'Archived' },
        ],
      },
    ],
    formFields: [
      { key: 'name', label: 'Name', col: 'col-md-6' },
      { key: 'email', label: 'Email', type: 'email', col: 'col-md-6' },
      { key: 'subject', label: 'Subject', col: 'col-md-8' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        col: 'col-md-4',
        options: [
          { value: 'new', label: 'New' },
          { value: 'read', label: 'Read' },
          { value: 'replied', label: 'Replied' },
          { value: 'archived', label: 'Archived' },
        ],
      },
      { key: 'message', label: 'Message', type: 'textarea' },
    ],
  },
  'ai-conversations': {
    key: 'ai-conversations',
    title: 'AI Conversations',
    titleSingular: 'AI Conversation',
    endpoint: '/ai-conversations',
    softDeletes: false,
    canCreate: false,
    formSize: 'xl',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'question', label: 'Question', accessor: (r) => (r.question || '').slice(0, 80) },
      { key: 'bible_version', label: 'Version' },
      { key: 'created_at', label: 'Date', format: 'datetime' },
    ],
    filters: [{ key: 'bible_version', label: 'Version', options: [] }],
    formFields: [
      { key: 'visitor_id', label: 'Visitor ID', col: 'col-md-6' },
      { key: 'bible_version', label: 'Bible Version', col: 'col-md-6' },
      { key: 'question', label: 'Question', type: 'textarea' },
      { key: 'answer', label: 'Answer', type: 'textarea' },
      {
        key: 'bible_references',
        label: 'Scripture References',
        type: 'multiselect',
        objectKey: 'reference',
        optionsFromData: true,
        col: 'col-12',
        help: 'Toggle which Scripture references are stored with this conversation.',
      },
    ],
  },
  'page-visits': {
    key: 'page-visits',
    title: 'Page Visits',
    titleSingular: 'Page Visit',
    endpoint: '/page-visits',
    canCreate: false,
    softDeletes: false,
    canImport: false,
    columns: [
      { key: 'visited_at', label: 'Visited', format: 'datetime' },
      { key: 'page_type', label: 'Type' },
      { key: 'page_title', label: 'Title' },
      { key: 'page_slug', label: 'Slug' },
      { key: 'visitor_id', label: 'Visitor' },
    ],
    filters: [{ key: 'page_type', label: 'Page Type', options: [] }],
    formFields: [
      { key: 'visitor_id', label: 'Visitor ID', col: 'col-md-6' },
      { key: 'page_type', label: 'Page Type', required: true, col: 'col-md-6' },
      { key: 'page_title', label: 'Page Title', col: 'col-md-6' },
      { key: 'page_slug', label: 'Page Slug', col: 'col-md-6' },
      { key: 'visited_at', label: 'Visited At', type: 'datetime-local', col: 'col-md-6' },
    ],
  },
};

export function getResourceConfig(key) {
  return resourceConfigs[key] || null;
}
