<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Curated Scripture Topics (fallback when OpenAI is unavailable)
    |--------------------------------------------------------------------------
    |
    | Each topic matches user questions by keywords and returns known passages
    | with brief pastoral guidance grounded in Catholic teaching.
    |
    */

    'topics' => [
        'sexuality' => [
            'keywords' => [
                'gay',
                'lesbian',
                'homosexual',
                'homosexuality',
                'same-sex',
                'same sex',
                'lgbt',
                'lgbtq',
                'sexual orientation',
                'bisexual',
            ],
            'references' => [
                'Genesis 1:27',
                'Genesis 2:24',
                'Leviticus 18:22',
                'Romans 1:26-27',
                '1 Corinthians 6:9-10',
                '1 Corinthians 6:18-20',
            ],
            'guidance' => [
                'Scripture presents human sexuality as part of God\'s good creation, ordered toward love, fidelity, and openness to life within marriage between a man and a woman.',
                'The Church teaches that persons who experience same-sex attraction are called to chastity, as all people are, and should be treated with respect, compassion, and sensitivity.',
                'If you are wrestling with this question, consider speaking with a priest or spiritual director who can help you discern God\'s will with charity and truth.',
            ],
        ],

        'marriage' => [
            'keywords' => [
                'marriage',
                'married',
                'husband',
                'wife',
                'spouse',
                'wedding',
                'matrimony',
            ],
            'references' => [
                'Genesis 2:24',
                'Matthew 19:4-6',
                'Ephesians 5:25-33',
                '1 Corinthians 7:10-11',
                'Hebrews 13:4',
            ],
            'guidance' => [
                'Marriage is a sacred covenant reflecting Christ\'s faithful love for the Church.',
                'Scripture calls spouses to mutual love, forgiveness, and fidelity through every season of life.',
            ],
        ],

        'divorce' => [
            'keywords' => [
                'divorce',
                'divorced',
                'separation',
                'annulment',
                'remarry',
                'remarriage',
            ],
            'references' => [
                'Malachi 2:16',
                'Matthew 5:31-32',
                'Matthew 19:6-9',
                '1 Corinthians 7:10-15',
                'Mark 10:11-12',
            ],
            'guidance' => [
                'God\'s plan for marriage is permanence and fidelity, yet Scripture also acknowledges the painful realities of broken relationships.',
                'If you are affected by divorce, the Church offers pastoral care; speak with a priest about healing, reconciliation, and the possibility of annulment where applicable.',
            ],
        ],

        'anxiety' => [
            'keywords' => [
                'anxiety',
                'anxious',
                'worry',
                'worried',
                'stress',
                'stressed',
                'overwhelmed',
                'fearful',
            ],
            'references' => [
                'Psalm 23:1-4',
                'Psalm 56:3',
                'Matthew 6:25-34',
                'Philippians 4:6-7',
                '1 Peter 5:7',
            ],
            'guidance' => [
                'Scripture repeatedly invites us to cast our cares upon God, who sustains us in every trial.',
                'Bring your fears to prayer, and trust that the Lord walks with you even when the path feels uncertain.',
            ],
        ],

        'depression' => [
            'keywords' => [
                'depression',
                'depressed',
                'sadness',
                'hopeless',
                'despair',
                'grief',
                'lonely',
                'loneliness',
            ],
            'references' => [
                'Psalm 34:18',
                'Psalm 42:5',
                'Isaiah 41:10',
                'Matthew 11:28-30',
                'Romans 8:38-39',
            ],
            'guidance' => [
                'The Psalms give voice to deep sorrow, showing that honest prayer before God is never wasted.',
                'If you are struggling with persistent sadness, seek both spiritual support and appropriate professional help; God works through both grace and human care.',
            ],
        ],

        'forgiveness' => [
            'keywords' => [
                'forgive',
                'forgiveness',
                'forgiving',
                'grudge',
                'resentment',
                'reconcile',
                'reconciliation',
            ],
            'references' => [
                'Matthew 6:14-15',
                'Matthew 18:21-22',
                'Luke 6:37',
                'Ephesians 4:32',
                'Colossians 3:13',
            ],
            'guidance' => [
                'Forgiveness is a grace that frees the heart and reflects the mercy God has shown us in Christ.',
                'Forgiveness does not always mean immediate trust or closeness, but it does mean releasing bitterness and entrusting justice to God.',
            ],
        ],

        'prayer' => [
            'keywords' => [
                'prayer',
                'pray',
                'praying',
                'rosary',
                'meditation',
                'contemplation',
                'intercession',
            ],
            'references' => [
                'Matthew 6:6-13',
                'Luke 18:1',
                'Romans 8:26',
                'Philippians 4:6',
                '1 Thessalonians 5:17',
            ],
            'guidance' => [
                'Prayer is conversation with God: speaking honestly from the heart and listening in silence.',
                'Even brief, imperfect prayers are heard; consistency and humility matter more than eloquence.',
            ],
        ],

        'faith_doubt' => [
            'keywords' => [
                'faith',
                'believe',
                'belief',
                'doubt',
                'doubting',
                'doubts',
                'trust god',
                'trust in god',
                'lose faith',
                'lost faith',
                'questioning god',
                'question god',
                'uncertain',
                'uncertainty',
                'skepticism',
                'skeptical',
                'crisis of faith',
                'struggle to believe',
                'hard to believe',
                'why believe',
                'does god exist',
                'existence of god',
            ],
            'references' => [
                'Mark 9:24',
                'John 20:24-29',
                'Hebrews 11:1',
                'James 1:5-6',
                'Romans 10:17',
                'Psalm 42:5',
            ],
            'guidance' => [
                'Even saints and apostles wrestled with doubt; Thomas asked for proof, and the Lord met him with patience.',
                'Faith is a gift that grows through Scripture, sacraments, and honest conversation with God and the Church.',
                'Bring your questions without shame, and ask the Holy Spirit to strengthen what feels weak in you.',
            ],
        ],

        'salvation' => [
            'keywords' => [
                'salvation',
                'saved',
                'save me',
                'heaven',
                'eternal life',
                'redeemed',
                'redeemer',
            ],
            'references' => [
                'John 3:16-17',
                'Romans 6:23',
                'Ephesians 2:8-9',
                'Titus 3:5-7',
                '1 John 1:9',
            ],
            'guidance' => [
                'Salvation is God\'s free gift in Jesus Christ, received through faith and lived in obedience to His word.',
                'Turn to the Lord in repentance and receive the grace offered through Baptism, Confession, and the Eucharist.',
            ],
        ],

        'sin_repentance' => [
            'keywords' => [
                'sin',
                'sinner',
                'sinning',
                'repent',
                'repentance',
                'confession',
                'guilt',
                'temptation',
                'tempted',
            ],
            'references' => [
                '1 John 1:8-9',
                'Proverbs 28:13',
                'Acts 3:19',
                'James 4:7-8',
                '1 Corinthians 10:13',
            ],
            'guidance' => [
                'God does not abandon the repentant heart; His mercy is greater than any failure.',
                'When you fall, rise again through confession and resolve to walk more closely with Christ.',
            ],
        ],

        'anger' => [
            'keywords' => [
                'anger',
                'angry',
                'rage',
                'wrath',
                'bitter',
                'irritable',
                'temper',
            ],
            'references' => [
                'Ephesians 4:26-27',
                'James 1:19-20',
                'Proverbs 15:1',
                'Colossians 3:8',
                'Matthew 5:9',
            ],
            'guidance' => [
                'Scripture acknowledges righteous anger yet warns against letting it become a foothold for sin.',
                'Ask the Holy Spirit for self-control, and seek reconciliation where your anger has wounded others.',
            ],
        ],

        'love_charity' => [
            'keywords' => [
                'love',
                'charity',
                'compassion',
                'kindness',
                'mercy',
                'serve others',
                'neighbor',
            ],
            'references' => [
                'Romans 13:8-10',
                'John 13:34-35',
                '1 John 4:7-8',
                'Matthew 25:40',
                'Luke 10:27',
            ],
            'guidance' => [
                'Christian love is not mere feeling but a deliberate choice to seek the good of others as Christ loved us.',
                'Look for concrete ways to serve those in need, beginning with patience and generosity at home.',
            ],
        ],

        'suffering' => [
            'keywords' => [
                'suffering',
                'suffer',
                'pain',
                'trial',
                'hardship',
                'affliction',
                'cross',
                'persecution',
            ],
            'references' => [
                'Romans 8:18',
                '2 Corinthians 12:9-10',
                '1 Peter 4:12-13',
                'Job 1:21',
                'John 16:33',
            ],
            'guidance' => [
                'Christ entered human suffering and transformed it through the Cross, offering meaning and hope.',
                'Offer your trials in union with Jesus, trusting that God can bring good even from what wounds us deeply.',
            ],
        ],

        'death_grief' => [
            'keywords' => [
                'death',
                'dying',
                'died',
                'grief',
                'mourning',
                'funeral',
                'afterlife',
                'heaven',
                'hell',
            ],
            'references' => [
                'John 11:25-26',
                'Revelation 21:4',
                '1 Thessalonians 4:13-14',
                'Psalm 23:4',
                'Wisdom 3:1-3',
            ],
            'guidance' => [
                'Jesus wept at the grave of Lazarus and promises resurrection to those who believe in Him.',
                'Pray for the faithful departed, support the grieving, and hold fast to the hope of eternal life.',
            ],
        ],

        'money_wealth' => [
            'keywords' => [
                'money',
                'wealth',
                'rich',
                'poor',
                'greed',
                'greedy',
                'stewardship',
                'tithe',
                'offering',
                'finances',
            ],
            'references' => [
                'Matthew 6:24',
                'Luke 12:15',
                '1 Timothy 6:10',
                'Proverbs 22:7',
                'Malachi 3:10',
            ],
            'guidance' => [
                'Scripture warns that love of money can lead us away from God while calling us to generous stewardship.',
                'Use material goods responsibly, care for the poor, and remember that your true treasure is in heaven.',
            ],
        ],

        'parenting' => [
            'keywords' => [
                'parent',
                'parenting',
                'children',
                'child',
                'raise',
                'discipline',
                'family',
            ],
            'references' => [
                'Proverbs 22:6',
                'Ephesians 6:4',
                'Deuteronomy 6:6-7',
                'Colossians 3:21',
                'Psalm 127:3',
            ],
            'guidance' => [
                'Parents are called to teach the faith by word and example, forming their children in virtue and prayer.',
                'Discipline with patience and love, remembering that children learn Christ chiefly through your witness.',
            ],
        ],

        'abortion' => [
            'keywords' => [
                'abortion',
                'abort',
                'unborn',
                'pregnancy',
                'pregnant',
                'pro-life',
                'pro life',
            ],
            'references' => [
                'Psalm 139:13-16',
                'Jeremiah 1:5',
                'Exodus 20:13',
                'Luke 1:41-44',
                'Isaiah 49:15',
            ],
            'guidance' => [
                'Scripture affirms the dignity of human life from its earliest beginnings as known and loved by God.',
                'If you or someone you know faces a difficult pregnancy, seek pastoral and practical support that upholds both mother and child.',
            ],
        ],

        'addiction' => [
            'keywords' => [
                'addiction',
                'addicted',
                'alcohol',
                'drunk',
                'drugs',
                'substance',
                'porn',
                'pornography',
            ],
            'references' => [
                '1 Corinthians 6:12',
                'Galatians 5:22-23',
                'Romans 7:19-25',
                'Psalm 51:10-12',
                'James 5:16',
            ],
            'guidance' => [
                'No habit is stronger than the grace of Christ, yet healing often requires humility, community, and professional help.',
                'Confess your struggle, ask for accountability, and take one step at a time toward freedom in the Lord.',
            ],
        ],

        'lying_honesty' => [
            'keywords' => [
                'lie',
                'lying',
                'honest',
                'honesty',
                'truth',
                'deceive',
                'deception',
                'integrity',
            ],
            'references' => [
                'Exodus 20:16',
                'Proverbs 12:22',
                'Ephesians 4:25',
                'John 8:32',
                'Revelation 21:8',
            ],
            'guidance' => [
                'God is truth, and His people are called to speak honestly even when the truth is costly.',
                'Repent of falsehood, make amends where possible, and build a habit of transparent speech.',
            ],
        ],

        'peace' => [
            'keywords' => [
                'peace',
                'peaceful',
                'calm',
                'rest',
                'tranquil',
                'inner peace',
            ],
            'references' => [
                'John 14:27',
                'Isaiah 26:3',
                'Philippians 4:7',
                'Colossians 3:15',
                'Psalm 29:11',
            ],
            'guidance' => [
                'The peace Christ gives is not the absence of trouble but the presence of God within it.',
                'Return to prayer and the sacraments, where the Lord restores a heart troubled by the world.',
            ],
        ],

        'war' => [
            'keywords' => [
                'war',
                'warfare',
                'battle',
                'combat',
                'military',
                'soldier',
                'soldiers',
                'invasion',
                'armed conflict',
                'kill in war',
                'killing in war',
                'just war',
                'violence',
                'weapon',
                'weapons',
                'army',
                'navy',
                'defend country',
                'self-defense',
                'self defense',
            ],
            'references' => [
                'Isaiah 2:4',
                'Matthew 5:9',
                'Romans 12:18-21',
                'Ecclesiastes 3:8',
                'Proverbs 24:6',
                'Luke 3:14',
            ],
            'guidance' => [
                'Scripture longs for the day when nations will beat swords into plowshares, yet it also acknowledges the tragic reality of war in a fallen world.',
                'The Church teaches that legitimate defense may be necessary while always preferring peace, protecting civilians, and rejecting hatred toward enemies.',
                'If war touches you personally, pray for the fallen, support the suffering, and work for justice and reconciliation where you can.',
            ],
        ],

        'corruption' => [
            'keywords' => [
                'corruption',
                'corrupt',
                'bribery',
                'bribe',
                'bribes',
                'graft',
                'embezzle',
                'embezzlement',
                'kickback',
                'dishonest official',
                'dishonest government',
                'fraud',
                'fraudulent',
                'racket',
                'public office',
                'political corruption',
                'stealing public',
                'misuse of power',
            ],
            'references' => [
                'Proverbs 17:23',
                'Proverbs 28:16',
                'Isaiah 1:23',
                'Micah 3:11',
                'Amos 5:12',
                'Luke 16:10',
            ],
            'guidance' => [
                'Scripture condemns leaders who pervert justice for personal gain and warns that dishonest scales cannot stand before God.',
                'Christians are called to integrity in public and private life, refusing bribes and speaking up for the poor who suffer most from corruption.',
                'If you witness corruption, pursue lawful remedies, act with courage and prudence, and pray that society be renewed in righteousness.',
            ],
        ],

        'transgender' => [
            'keywords' => [
                'transgender',
                'trans',
                'gender identity',
                'gender dysphoria',
                'transition',
                'transitioning',
                'non-binary',
                'nonbinary',
                'gender fluid',
                'genderfluid',
                'change gender',
                'born in wrong body',
            ],
            'references' => [
                'Genesis 1:27',
                'Genesis 2:24',
                'Psalm 139:13-16',
                'Deuteronomy 22:5',
                'Galatians 6:15',
                'Matthew 19:4',
            ],
            'guidance' => [
                'Scripture teaches that God creates each person body and soul, male or female, with inherent dignity and purpose.',
                'The Church calls every person to accept and live in harmony with the gift of their body, while offering compassion to those who experience deep inner conflict.',
                'If you struggle with questions of identity, seek a priest or counselor who can walk with you in truth, mercy, and pastoral care.',
            ],
        ],

        'hypocrisy' => [
            'keywords' => [
                'hypocrisy',
                'hypocrite',
                'hypocritical',
                'hypocrites',
                'two-faced',
                'two faced',
                'fake christian',
                'fake catholic',
                'false piety',
                'pretend to be holy',
                'pharisee',
                'pharisees',
                'say one thing',
                'do another',
                'virtue signaling',
            ],
            'references' => [
                'Matthew 23:27-28',
                'Luke 12:1',
                'James 1:22',
                '1 John 2:4',
                'Titus 1:16',
                'Isaiah 29:13',
            ],
            'guidance' => [
                'Jesus strongly condemned those who appeared righteous outwardly while their hearts were far from God.',
                'Examine your own conscience first: faith must be lived, not merely professed, and repentance begins with honesty before the Lord.',
                'When others act hypocritically, do not let their failure destroy your pursuit of sincere holiness and charity.',
            ],
        ],

        'treason' => [
            'keywords' => [
                'treason',
                'traitor',
                'traitors',
                'betrayal',
                'betray',
                'betrayed',
                'betraying',
                'betrayer',
                'disloyal',
                'disloyalty',
                'turn against',
                'sell out',
                'sold out',
                'double agent',
                'break trust',
                'broken trust',
                'Judas',
            ],
            'references' => [
                'Proverbs 25:19',
                'Psalm 41:9',
                'Proverbs 27:6',
                'Luke 22:48',
                'Psalm 55:12-14',
                '2 Samuel 15:12',
            ],
            'guidance' => [
                'Scripture treats betrayal as a grave wound, for trust is sacred and its violation brings deep pain to individuals and communities.',
                'Judas betrayed Christ with a kiss, showing that treachery can hide beneath the appearance of friendship; guard your heart and choose loyalty to truth.',
                'If you have been betrayed, entrust your hurt to God who is faithful; if you have betrayed another, seek repentance and make restitution where possible.',
            ],
        ],

        // ── Government & civic life ──────────────────────────────────────

        'government_authority' => [
            'keywords' => [
                'government',
                'governments',
                'authority',
                'authorities',
                'ruler',
                'rulers',
                'civil authority',
                'state',
                'nation state',
                'public official',
                'public officials',
                'magistrate',
                'magistrates',
                'obey the law',
                'obey laws',
                'submission to authority',
                'render unto caesar',
                'political leader',
                'political leaders',
                'prime minister',
                'president',
                'governor',
                'mayor',
                'parliament',
                'congress',
                'senate',
                'legislature',
                'cabinet',
                'administration',
            ],
            'references' => [
                'Romans 13:1-7',
                '1 Peter 2:13-17',
                'Titus 3:1',
                'Proverbs 28:16',
                'Daniel 2:21',
                '1 Timothy 2:1-2',
            ],
            'guidance' => [
                'Scripture teaches that governing authority comes from God and exists to restrain evil and promote the common good.',
                'Christians owe lawful obedience, prayer for leaders, and honest civic participation, while never placing any state above God.',
            ],
        ],

        'civil_disobedience' => [
            'keywords' => [
                'civil disobedience',
                'unjust law',
                'unjust laws',
                'disobey government',
                'disobey authority',
                'when to disobey',
                'illegal but moral',
                'conscientious objection',
                'refuse unjust order',
                'must obey god rather than men',
                'defy tyrant',
                'illegal worship',
                'forbidden to pray',
            ],
            'references' => [
                'Acts 5:29',
                'Daniel 3:16-18',
                'Daniel 6:10',
                'Exodus 1:17',
                'Acts 4:19-20',
                'Hebrews 11:23',
            ],
            'guidance' => [
                'When human law directly contradicts divine law, the faithful must obey God first, accepting the consequences with courage.',
                'Civil disobedience is justified only for grave injustice, pursued without hatred, and never as an excuse for personal rebellion.',
            ],
        ],

        'elections_politics' => [
            'keywords' => [
                'election',
                'elections',
                'vote',
                'voting',
                'voter',
                'ballot',
                'democracy',
                'democratic',
                'political party',
                'political parties',
                'campaign',
                'campaigns',
                'candidate',
                'candidates',
                'politics',
                'political',
                'politician',
                'politicians',
                'partisan',
                'referendum',
            ],
            'references' => [
                'Proverbs 28:16',
                'Isaiah 10:1-2',
                'Micah 6:8',
                'Matthew 22:21',
                '1 Timothy 2:1-2',
            ],
            'guidance' => [
                'Scripture commends rulers who pursue justice and warns against leaders who exploit the weak for personal gain.',
                'In democratic societies, voting is a moral act: choose leaders and policies that protect life, promote justice, and serve the common good.',
            ],
        ],

        'tyranny_oppression' => [
            'keywords' => [
                'tyranny',
                'tyrant',
                'tyrants',
                'dictator',
                'dictatorship',
                'dictators',
                'oppression',
                'oppress',
                'oppressed',
                'oppressor',
                'oppressors',
                'authoritarian',
                'totalitarian',
                'police state',
                'persecute citizens',
                'crackdown',
                'suppress dissent',
                'abuse of power',
                'unjust ruler',
            ],
            'references' => [
                'Isaiah 10:1-2',
                'Jeremiah 22:3',
                'Ezekiel 22:29',
                'Psalm 82:3-4',
                'Ecclesiastes 5:8',
                'Wisdom 6:7',
            ],
            'guidance' => [
                'The prophets denounced rulers who crushed the poor and perverted justice, for God hears the cry of the oppressed.',
                'Christians must resist tyranny through truth, solidarity with victims, lawful means, and prayer—not through hatred or unjust violence.',
            ],
        ],

        'justice_law_courts' => [
            'keywords' => [
                'justice',
                'injustice',
                'court',
                'courts',
                'judge',
                'judges',
                'judgment',
                'judiciary',
                'law',
                'laws',
                'legal system',
                'verdict',
                'trial',
                'trials',
                'due process',
                'sentence',
                'sentencing',
                'prosecution',
                'defense attorney',
                'lawyer',
                'lawyers',
                'statute',
                'legislation',
            ],
            'references' => [
                'Deuteronomy 16:18-20',
                'Exodus 23:6',
                'Amos 5:12',
                'Micah 6:8',
                'Proverbs 22:22',
                'Isaiah 1:17',
            ],
            'guidance' => [
                'God commands judges to decide impartially, without favor to rich or poor, for justice is the foundation of social peace.',
                'Society must protect the innocent, punish wrongdoing proportionately, and remember that every person bears God-given dignity.',
            ],
        ],

        'taxes_civic_duty' => [
            'keywords' => [
                'tax',
                'taxes',
                'taxation',
                'tribute',
                'civic duty',
                'civic duties',
                'public service',
                'public servant',
                'civil service',
                'government revenue',
                'pay taxes',
                'tax collector',
                'tax collectors',
                'customs',
                'levy',
                'levies',
            ],
            'references' => [
                'Matthew 22:21',
                'Mark 12:17',
                'Luke 20:25',
                'Romans 13:6-7',
                'Luke 3:12-13',
                'Malachi 3:5',
            ],
            'guidance' => [
                'Jesus acknowledged civic obligations while teaching that ultimate loyalty belongs to God alone.',
                'Pay what is justly owed, demand accountability from leaders, and use your resources also for charity and the works of mercy.',
            ],
        ],

        'immigration_refugees' => [
            'keywords' => [
                'immigration',
                'immigrant',
                'immigrants',
                'migrant',
                'migrants',
                'refugee',
                'refugees',
                'asylum',
                'border',
                'borders',
                'foreigner',
                'foreigners',
                'stranger',
                'strangers',
                'alien',
                'aliens',
                'sojourner',
                'sojourners',
                'xenophobia',
                'deportation',
                'sanctuary',
            ],
            'references' => [
                'Leviticus 19:33-34',
                'Exodus 22:21',
                'Deuteronomy 10:19',
                'Matthew 25:35',
                'Hebrews 13:2',
                'Tobit 4:9',
            ],
            'guidance' => [
                'Scripture repeatedly commands love and fair treatment of the foreigner, remembering that Israel too was once a stranger in Egypt.',
                'Nations may regulate borders prudently, yet must never abandon the dignity, safety, and basic needs of those fleeing harm or seeking a lawful home.',
            ],
        ],

        'death_penalty' => [
            'keywords' => [
                'death penalty',
                'capital punishment',
                'execution',
                'executions',
                'execute criminals',
                'death sentence',
                'life for life',
                'eye for eye',
                'death row',
            ],
            'references' => [
                'Genesis 9:6',
                'Exodus 21:12',
                'Deuteronomy 17:6',
                'Romans 12:19',
                'John 8:7',
                'Ezekiel 33:11',
            ],
            'guidance' => [
                'Scripture recognizes the sacredness of human life and the state\'s duty to restrain grave evil, while also pointing toward mercy and restraint.',
                'The Church today urges societies to seek non-lethal means of justice wherever possible, without denying the horror of murder or the need for public order.',
            ],
        ],

        'nationalism_patriotism' => [
            'keywords' => [
                'patriotism',
                'patriotic',
                'nationalism',
                'nationalist',
                'nation',
                'nations',
                'country',
                'homeland',
                'fatherland',
                'motherland',
                'citizen',
                'citizens',
                'citizenship',
                'flag',
                'sovereignty',
                'independence day',
                'love of country',
            ],
            'references' => [
                'Acts 17:26',
                'Deuteronomy 32:7',
                'Psalm 33:12',
                'Jeremiah 29:7',
                '1 Peter 2:17',
                'Galatians 3:28',
            ],
            'guidance' => [
                'God sets the nations in their place and calls peoples to honor their heritage without idolizing blood, soil, or power.',
                'True patriotism serves the common good and welcomes the stranger; it never replaces the universal brotherhood redeemed in Christ.',
            ],
        ],

        'rebellion_revolution' => [
            'keywords' => [
                'rebellion',
                'rebel',
                'rebels',
                'revolution',
                'revolutionary',
                'revolt',
                'uprising',
                'insurrection',
                'coup',
                'overthrow government',
                'overthrow the king',
                'regime change',
                'armed uprising',
                'civil war',
            ],
            'references' => [
                'Romans 13:2',
                '1 Samuel 15:23',
                'Proverbs 24:21-22',
                'Ecclesiastes 10:4',
                '2 Maccabees 2:19-20',
                'Acts 5:29',
            ],
            'guidance' => [
                'Scripture warns against reckless revolt while also recording times when faith required resistance to idolatrous or murderous rulers.',
                'Any use of force in political change demands rigorous moral scrutiny, protection of innocents, and obedience to God above all.',
            ],
        ],

        // ── Society & social life ──────────────────────────────────────────

        'poverty_social_justice' => [
            'keywords' => [
                'poverty',
                'poor',
                'homeless',
                'homelessness',
                'hunger',
                'hungry',
                'food insecurity',
                'social justice',
                'economic justice',
                'inequality',
                'wealth gap',
                'exploitation',
                'exploit the poor',
                'minimum wage',
                'labor rights',
                'unfair wages',
                'worker exploitation',
            ],
            'references' => [
                'Isaiah 58:6-7',
                'James 1:27',
                'Psalm 146:7-9',
                'Luke 1:52-53',
                'Proverbs 19:17',
                'Nehemiah 5:1-5',
            ],
            'guidance' => [
                'True religion includes care for orphans, widows, and the poor kept unstained by the world.',
                'Christians must work personally and socially to relieve hunger, shelter the homeless, and reform structures that crush the vulnerable.',
            ],
        ],

        'racism_discrimination' => [
            'keywords' => [
                'racism',
                'racist',
                'racial',
                'discrimination',
                'discriminate',
                'prejudice',
                'prejudiced',
                'bigotry',
                'bigot',
                'ethnic hatred',
                'ethnic conflict',
                'superior race',
                'inferior race',
                'segregation',
                'xenophobia',
                'tribalism',
            ],
            'references' => [
                'James 2:1-9',
                'Galatians 3:28',
                'Colossians 3:11',
                'Acts 10:34-35',
                'Genesis 1:27',
                'Leviticus 19:18',
            ],
            'guidance' => [
                'God shows no partiality; every person is made in His image and called to one dignity in Christ.',
                'Reject contempt based on ethnicity or status, repent of prejudice, and build communities that reflect the unity of the human family.',
            ],
        ],

        'slavery' => [
            'keywords' => [
                'slavery',
                'slave',
                'slaves',
                'enslaved',
                'enslavement',
                'human trafficking',
                'trafficking',
                'forced labor',
                'bondage',
                'abolition',
                'slave trade',
            ],
            'references' => [
                'Exodus 21:16',
                'Exodus 1:11-14',
                '1 Timothy 1:10',
                'Philemon 1:15-16',
                'Galatians 3:28',
                'Isaiah 58:6',
            ],
            'guidance' => [
                'Scripture condemns man-stealing and records God\'s liberation of Israel from cruel bondage as a sign of His saving mercy.',
                'Every form of human trafficking or slavery is an grave offense against human dignity and must be resisted and dismantled.',
            ],
        ],

        'crime_society' => [
            'keywords' => [
                'crime',
                'crimes',
                'criminal',
                'criminals',
                'theft',
                'stealing',
                'robbery',
                'murder',
                'violence in society',
                'gang',
                'gangs',
                'kidnapping',
                'assault',
                'unsafe streets',
                'lawlessness',
                'public safety',
            ],
            'references' => [
                'Exodus 20:13-15',
                'Romans 13:3-4',
                'Proverbs 1:10-16',
                'Ephesians 4:28',
                'Genesis 4:9-10',
                'Wisdom 14:30',
            ],
            'guidance' => [
                'The commandments protect life, property, and trust—the foundations of any humane society.',
                'Communities must restrain violence, restore offenders where possible, and address the poverty and injustice that often breed crime.',
            ],
        ],

        'environment_stewardship' => [
            'keywords' => [
                'environment',
                'environmental',
                'climate',
                'climate change',
                'pollution',
                'pollute',
                'creation care',
                'stewardship of earth',
                'ecology',
                'ecological',
                'deforestation',
                'natural resources',
                'planet',
                'global warming',
                'care for creation',
            ],
            'references' => [
                'Genesis 2:15',
                'Genesis 1:28',
                'Isaiah 24:4-6',
                'Wisdom 13:5',
                'Psalm 104:24',
                'Romans 8:19-22',
            ],
            'guidance' => [
                'God entrusted the earth to human care as stewards, not as owners free to waste or destroy.',
                'Use resources responsibly, protect the poor who suffer first from environmental harm, and honor the Creator in how we treat His works.',
            ],
        ],

        'education_wisdom_society' => [
            'keywords' => [
                'education',
                'school',
                'schools',
                'university',
                'universities',
                'teaching',
                'teacher',
                'teachers',
                'student',
                'students',
                'learning',
                'literacy',
                'scholarship',
                'wisdom tradition',
                'philosophy',
                'knowledge',
                'study',
                'studies',
                'catechism class',
            ],
            'references' => [
                'Proverbs 1:7',
                'Sirach 38:1',
                'Deuteronomy 6:6-7',
                '2 Timothy 3:16',
                'Colossians 3:16',
                'Wisdom 6:17',
            ],
            'guidance' => [
                'The fear of the Lord is the beginning of wisdom; all true learning should lead the mind toward truth and virtue.',
                'Parents, teachers, and churches share the duty to form young people in faith, reason, and service to neighbor.',
            ],
        ],

        'widow_orphan_vulnerable' => [
            'keywords' => [
                'widow',
                'widows',
                'orphan',
                'orphans',
                'vulnerable',
                'marginalized',
                'outcast',
                'outcasts',
                'disability',
                'disabled',
                'elderly',
                'elder abuse',
                'neglect the poor',
                'forgotten people',
            ],
            'references' => [
                'James 1:27',
                'Psalm 146:7-9',
                'Isaiah 1:17',
                'Deuteronomy 24:17',
                'Job 29:12-16',
                'Sirach 4:8',
            ],
            'guidance' => [
                'Scripture singles out widows, orphans, and the poor as special recipients of God\'s concern and ours.',
                'A just society protects those who cannot protect themselves and ensures that no one is discarded as worthless.',
            ],
        ],

        'idolatry_worldly_culture' => [
            'keywords' => [
                'idolatry',
                'idol',
                'idols',
                'worldliness',
                'worldly culture',
                'materialism',
                'consumerism',
                'celebrity worship',
                'fame',
                'status',
                'vanity',
                'secularism',
                'godless society',
                'culture of death',
                'moral decline',
            ],
            'references' => [
                'Exodus 20:3-5',
                '1 John 2:15-16',
                'Romans 12:2',
                'Deuteronomy 6:14-15',
                'Psalm 115:4-8',
                'Matthew 6:24',
            ],
            'guidance' => [
                'When culture elevates pleasure, power, or profit above God, it becomes a new form of idol worship.',
                'Christians are called to live in the world without conforming to its empty values, witnessing to eternal truth with joy.',
            ],
        ],

        'neighbor_community' => [
            'keywords' => [
                'community',
                'communities',
                'neighbor',
                'neighbors',
                'neighbour',
                'neighbours',
                'civic life',
                'common good',
                'solidarity',
                'social harmony',
                'public life',
                'civil society',
                'volunteer',
                'volunteering',
                'charity work',
                'good samaritan',
            ],
            'references' => [
                'Luke 10:25-37',
                'Matthew 7:12',
                'Romans 14:13',
                '1 Peter 4:8',
                'Galatians 6:2',
                'Hebrews 10:24',
            ],
            'guidance' => [
                'The law and the prophets hang on love of God and love of neighbor; citizenship in heaven begins with service on earth.',
                'Build up your community through patience, forgiveness, and concrete acts of mercy toward those nearest you.',
            ],
        ],

        // ── History & providence ───────────────────────────────────────────

        'covenant_israel_history' => [
            'keywords' => [
                'israel history',
                'history of israel',
                'chosen people',
                'covenant',
                'covenants',
                'abraham',
                'patriarchs',
                'twelve tribes',
                'promised land',
                'old testament history',
                'biblical history',
                'holy land history',
            ],
            'references' => [
                'Genesis 12:1-3',
                'Genesis 17:7',
                'Exodus 19:5-6',
                'Deuteronomy 7:6',
                'Psalm 105:8-10',
                'Romans 9:4-5',
            ],
            'guidance' => [
                'God entered history through a people chosen to preserve faith, law, and the promise of the Messiah for all nations.',
                'Israel\'s story reveals both God\'s fidelity and human failure, preparing the world for the redemption fulfilled in Christ.',
            ],
        ],

        'exodus_deliverance' => [
            'keywords' => [
                'exodus',
                'passover',
                'liberation',
                'deliverance',
                'freedom from slavery',
                'moses',
                'ten plagues',
                'red sea',
                'wilderness wandering',
                'promised land conquest',
            ],
            'references' => [
                'Exodus 12:41',
                'Exodus 14:13-14',
                'Deuteronomy 6:20-23',
                'Psalm 78:12-13',
                'Acts 7:35-36',
                '1 Corinthians 10:1-4',
            ],
            'guidance' => [
                'The Exodus remains the great sign that God hears the cry of the oppressed and leads His people toward freedom and worship.',
                'Every generation must remember this deliverance and allow it to inspire hope, gratitude, and justice toward the suffering.',
            ],
        ],

        'exile_restoration' => [
            'keywords' => [
                'exile',
                'babylon',
                'babylonian captivity',
                'captivity',
                'deportation',
                'return from exile',
                'restoration',
                'rebuilding temple',
                'ezra',
                'nehemiah',
                'post-exilic',
                'diaspora',
            ],
            'references' => [
                '2 Chronicles 36:21',
                'Ezra 1:1-3',
                'Jeremiah 29:10-14',
                'Psalm 137:1-4',
                'Isaiah 40:1-2',
                'Nehemiah 2:17',
            ],
            'guidance' => [
                'Exile came through unfaithfulness, yet God preserved a remnant and opened the way for repentance and return.',
                'National ruin is not the final word; God restores those who humble themselves and rebuild in faith.',
            ],
        ],

        'monarchy_kings' => [
            'keywords' => [
                'monarchy',
                'king',
                'kings',
                'kingdom',
                'kingdoms',
                'royal',
                'royalty',
                'crown',
                'saul',
                'david',
                'solomon',
                'dynasty',
                'succession',
                'anointing of king',
                'divine right',
            ],
            'references' => [
                '1 Samuel 8:4-7',
                '1 Samuel 16:13',
                '2 Samuel 7:12-16',
                '1 Kings 3:9',
                'Proverbs 16:12',
                'Daniel 4:17',
            ],
            'guidance' => [
                'Israel asked for a king like other nations; God granted monarchy while insisting that every ruler remain under divine judgment.',
                'Earthly kings pass away, but Christ\'s kingdom endures—history\'s true center is the throne of the crucified and risen Lord.',
            ],
        ],

        'nation_judgment_history' => [
            'keywords' => [
                'fall of nation',
                'fall of empire',
                'empire',
                'empires',
                'nation destroyed',
                'divine judgment on nation',
                'prophets and nations',
                'assyria',
                'babylon empire',
                'rome',
                'roman empire',
                'historical judgment',
                'rise and fall',
                'collapse of civilization',
            ],
            'references' => [
                'Isaiah 10:5-7',
                'Jeremiah 25:8-11',
                'Daniel 2:21',
                'Daniel 4:17',
                'Amos 1:3',
                'Revelation 18:2',
            ],
            'guidance' => [
                'The prophets announced that proud nations would answer to God for cruelty, idolatry, and the oppression of the innocent.',
                'No empire lasts forever; history warns the powerful to practice humility and calls the faithful to trust God when kingdoms shake.',
            ],
        ],

        'persecution_martyrs_history' => [
            'keywords' => [
                'martyr',
                'martyrs',
                'martyrdom',
                'persecution',
                'persecuted church',
                'persecuted christians',
                'early church persecution',
                'roman persecution',
                'nero',
                'arena',
                'witness unto death',
                'blood of martyrs',
                'maccabees',
                'holy martyrs',
            ],
            'references' => [
                'Acts 7:54-60',
                'Revelation 2:10',
                'Matthew 10:22',
                '2 Maccabees 7:1',
                'Hebrews 11:35-38',
                'Wisdom 3:1-4',
            ],
            'guidance' => [
                'From Stephen to the Maccabean martyrs, Scripture honors those who preferred death to betraying God.',
                'The blood of martyrs has strengthened the Church through the ages; their witness calls us to courage and fidelity today.',
            ],
        ],

        'creation_ancient_history' => [
            'keywords' => [
                'creation',
                'created world',
                'genesis',
                'adam and eve',
                'fall of man',
                'original sin',
                'flood',
                'noah',
                'noah\'s ark',
                'tower of babel',
                'babel',
                'ancient world',
                'prehistory',
                'beginning of humanity',
                'six days of creation',
            ],
            'references' => [
                'Genesis 1:1',
                'Genesis 2:7',
                'Genesis 3:6-7',
                'Genesis 6:5-8',
                'Genesis 11:1-9',
                'Wisdom 11:24',
            ],
            'guidance' => [
                'Scripture opens history with God creating all things good and entrusting humanity with freedom and responsibility.',
                'The Fall, the Flood, and Babel explain the brokenness of human civilization while pointing forward to redemption in Christ.',
            ],
        ],

        'divine_providence_history' => [
            'keywords' => [
                'providence',
                'god in history',
                'god and history',
                'historical providence',
                'meaning of history',
                'why did god allow',
                'historical event',
                'historical events',
                'turning point in history',
                'lessons from history',
                'remember the past',
                'learn from history',
            ],
            'references' => [
                'Deuteronomy 32:7',
                'Psalm 78:4',
                '1 Corinthians 10:11',
                'Romans 15:4',
                'Acts 17:26',
                'Ecclesiastes 3:1',
            ],
            'guidance' => [
                'Scripture teaches that past events were recorded so later generations might learn wisdom and avoid repeating unfaithfulness.',
                'God works within human freedom; history is not meaningless, for the Lord guides nations toward His purposes even through suffering.',
            ],
        ],

        // ── Church & ecclesial life ────────────────────────────────────────

        'church_authority_magisterium' => [
            'keywords' => [
                'church authority',
                'magisterium',
                'church teaching',
                'church teachings',
                'doctrine',
                'infallibility',
                'infallible',
                'papal infallibility',
                'church discipline',
                'canon law',
                'hierarchy',
                'holy see',
                'teaching office',
                'deposit of faith',
            ],
            'references' => [
                'Matthew 16:18-19',
                '1 Timothy 3:15',
                'Luke 10:16',
                'Matthew 18:17-18',
                '2 Thessalonians 2:15',
                'Acts 15:28',
            ],
            'guidance' => [
                'Christ founded the Church on the apostles and entrusted her with authority to teach, sanctify, and govern in His name.',
                'Receive the Church\'s doctrinal guidance with docility, examining it in light of Scripture and Tradition rather than private opinion alone.',
            ],
        ],

        'pope_papacy_clergy' => [
            'keywords' => [
                'pope',
                'papacy',
                'papal',
                'bishop',
                'bishops',
                'archbishop',
                'cardinal',
                'cardinals',
                'priest',
                'priests',
                'clergy',
                'pastor',
                'pastors',
                'deacon',
                'deacons',
                'vatican',
                'holy father',
                'successor of peter',
                'ordination',
                'holy orders',
            ],
            'references' => [
                'Matthew 16:18-19',
                'John 21:15-17',
                'Hebrews 13:17',
                'Ephesians 4:11-13',
                '1 Timothy 3:1-7',
                'Titus 1:7-9',
            ],
            'guidance' => [
                'The Pope and bishops continue the apostolic ministry, feeding the flock through word, sacrament, and governance.',
                'Pray for priests and bishops, obey lawful pastoral direction, and hold clergy accountable when they betray their sacred office.',
            ],
        ],

        'clergy_scandal_accountability' => [
            'keywords' => [
                'priest scandal',
                'clergy abuse',
                'church abuse',
                'sex abuse scandal',
                'abuse scandals',
                'abusive priest',
                'abusive clergy',
                'cover up',
                'cover-up',
                'church corruption',
                'bad priest',
                'bad bishop',
                'clericalism',
                'church scandal',
                'abuse in church',
            ],
            'references' => [
                'Matthew 18:6',
                'Luke 17:1-2',
                'Matthew 23:8-12',
                'Jeremiah 23:1-2',
                'Ezekiel 34:2-4',
                '1 Peter 5:2-3',
            ],
            'guidance' => [
                'Jesus warned severely against those who harm the little ones; no ministerial office excuses sin or shields abusers from justice.',
                'The Church must repent, protect victims, remove offenders, and reform structures so holiness and transparency define her leaders.',
            ],
        ],

        'christian_unity_ecumenism' => [
            'keywords' => [
                'ecumenism',
                'ecumenical',
                'christian unity',
                'church division',
                'denomination',
                'denominations',
                'protestant',
                'protestants',
                'reformation',
                'separated brethren',
                'interfaith dialogue',
                'different churches',
                'non-catholic christian',
                'orthodox church',
                'anglican',
            ],
            'references' => [
                'John 17:20-23',
                '1 Corinthians 1:10',
                'Ephesians 4:3-6',
                'Romans 15:5-7',
                '2 Corinthians 13:11',
                'Acts 15:28',
            ],
            'guidance' => [
                'Christ prayed that His disciples might be one so the world would believe; division among Christians wounds that witness.',
                'Pursue charity, truth, and dialogue with separated brethren while remaining faithful to the fullness of faith in the Catholic Church.',
            ],
        ],

        'schism_heresy' => [
            'keywords' => [
                'schism',
                'schismatic',
                'heresy',
                'heretic',
                'heretics',
                'false teaching',
                'false teachings',
                'apostasy',
                'apostate',
                'leave the church',
                'left the church',
                'cafeteria catholic',
                'cafeteria christian',
                'doctrinal error',
                'heterodoxy',
            ],
            'references' => [
                'Galatians 1:8',
                '1 John 2:19',
                '2 Timothy 4:3-4',
                'Titus 3:10',
                '1 Corinthians 11:18-19',
                '2 Peter 2:1',
            ],
            'guidance' => [
                'Scripture warns against teachers who distort the Gospel and communities that fracture the body of Christ.',
                'Hold fast to the faith delivered once for all, correcting error with clarity and never abandoning charity toward the erring.',
            ],
        ],

        'sacraments_liturgy' => [
            'keywords' => [
                'sacrament',
                'sacraments',
                'liturgy',
                'mass',
                'holy mass',
                'eucharist',
                'communion',
                'baptism',
                'confirmation',
                'confession',
                'reconciliation',
                'penance',
                'anointing of the sick',
                'holy orders sacrament',
                'matrimony sacrament',
                'adoration',
                'blessed sacrament',
                'liturgical',
            ],
            'references' => [
                'Acts 2:42',
                'Luke 22:19',
                'John 6:53-58',
                'Matthew 28:19',
                'James 5:14-15',
                '1 Corinthians 11:23-26',
            ],
            'guidance' => [
                'Christ instituted sacraments as visible signs of invisible grace, especially the Eucharist—the source and summit of Christian life.',
                'Receive the sacraments faithfully, prepare your heart before Mass, and let liturgical worship shape your daily conduct.',
            ],
        ],

        'sacred_tradition' => [
            'keywords' => [
                'tradition',
                'sacred tradition',
                'scripture and tradition',
                'sola scriptura',
                'bible alone',
                'oral tradition',
                'apostolic tradition',
                'church fathers',
                'teaching of the apostles',
                'interpret scripture',
                'biblical interpretation',
            ],
            'references' => [
                '2 Thessalonians 2:15',
                '2 Timothy 3:16',
                '1 Corinthians 11:2',
                'Jude 1:3',
                'Acts 2:42',
                'John 21:25',
            ],
            'guidance' => [
                'The apostles handed on Christ\'s teaching by word and example; the Church preserves this living Tradition alongside Scripture.',
                'Read the Bible within the communion of the Church, guided by her authoritative interpretation and centuries of faithful witness.',
            ],
        ],

        'evangelization_mission' => [
            'keywords' => [
                'evangelization',
                'evangelize',
                'mission',
                'missions',
                'missionary',
                'missionaries',
                'spread the gospel',
                'preach the gospel',
                'great commission',
                'new evangelization',
                'convert',
                'converts',
                'conversion of nations',
                'baptize all nations',
            ],
            'references' => [
                'Matthew 28:19-20',
                'Acts 1:8',
                'Romans 10:14-15',
                'Mark 16:15',
                'Acts 4:20',
                '1 Peter 3:15',
            ],
            'guidance' => [
                'Before ascending, the Lord commanded the Church to make disciples of all nations, baptizing and teaching them to observe His commands.',
                'Every Catholic is called to witness by word and life, inviting others to Christ with respect, joy, and confidence in the Gospel.',
            ],
        ],

        'parish_church_community' => [
            'keywords' => [
                'parish',
                'parishes',
                'local church',
                'congregation',
                'church community',
                'church membership',
                'go to church',
                'attend mass',
                'church attendance',
                'fellowship',
                'church family',
                'ministry',
                'ministries',
                'volunteer at church',
                'church group',
            ],
            'references' => [
                'Hebrews 10:25',
                '1 Corinthians 12:12-13',
                'Acts 2:42',
                'Ephesians 2:19-22',
                'Romans 12:4-5',
                '1 Peter 2:9',
            ],
            'guidance' => [
                'Believers belong to one body with many members; regular assembly for worship and service strengthens the whole Church.',
                'Invest yourself in your parish through prayer, sacraments, and the gifts God has given you for the good of others.',
            ],
        ],

        'church_persecution' => [
            'keywords' => [
                'persecute the church',
                'anti-catholic',
                'anti christian',
                'anti-christian',
                'church under attack',
                'religious persecution',
                'shutdown churches',
                'ban religion',
                'suppress christianity',
                'christian persecution today',
                'underground church',
            ],
            'references' => [
                'Matthew 10:22',
                'John 15:18-20',
                'Revelation 13:7',
                '2 Timothy 3:12',
                'Acts 8:1',
                '1 Peter 4:12-14',
            ],
            'guidance' => [
                'Christ warned that disciples would share in His sufferings; the Church has often grown stronger under persecution.',
                'Stand firm in faith, pray for the persecuted, and work for religious freedom so the Gospel may be preached without violence.',
            ],
        ],

        'temple_worship_holiness' => [
            'keywords' => [
                'temple',
                'sanctuary',
                'house of god',
                'house of worship',
                'church building',
                'desecration',
                'sacrilege',
                'holy place',
                'worship space',
                'tabernacle',
                'altar',
                'sacred space',
                'respect in church',
                'behavior in church',
            ],
            'references' => [
                '1 Kings 8:27',
                'Jeremiah 7:4',
                '1 Corinthians 3:16-17',
                'John 2:16',
                'Psalm 122:1',
                'Ephesians 2:19-22',
            ],
            'guidance' => [
                'God\'s house is set apart for prayer and sacrifice; reverence in worship reflects reverence for the Lord Himself.',
                'The Church is built of living stones—holiness of life matters more than stones, yet sacred places deserve honor and dignity.',
            ],
        ],

        'religious_orders_consecrated_life' => [
            'keywords' => [
                'religious order',
                'religious orders',
                'monk',
                'monks',
                'nun',
                'nuns',
                'convent',
                'monastery',
                'consecrated life',
                'vows',
                'vow of poverty',
                'vow of chastity',
                'vow of obedience',
                'friar',
                'sister',
                'brother religious',
                'contemplative',
                'missionary order',
            ],
            'references' => [
                'Matthew 19:12',
                '1 Corinthians 7:32-34',
                'Acts 2:44-45',
                'Luke 14:33',
                'Revelation 14:4',
                'Colossians 3:12',
            ],
            'guidance' => [
                'Consecrated life bears witness that God alone satisfies the heart and that the kingdom is worth every sacrifice.',
                'Religious communities serve the Church through prayer, poverty, and mission; honor their vocation and learn from their example.',
            ],
        ],

        'saints_intercession' => [
            'keywords' => [
                'saint',
                'saints',
                'canonization',
                'canonized',
                'intercession',
                'intercede',
                'patron saint',
                'blessed',
                'venerable',
                'hagiography',
                'communion of saints',
                'all saints',
            ],
            'references' => [
                'Hebrews 12:1',
                'Revelation 5:8',
                'James 5:16',
                'Wisdom 3:1',
                '1 Timothy 2:5',
            ],
            'guidance' => [
                'The Church on earth is united with the saints in heaven, who cheer us on and pray alongside us before the throne of God.',
                'Honor the saints as models of holiness and ask their intercession, while keeping Christ as the one mediator and head of all.',
            ],
        ],

        'marian_devotion' => [
            'keywords' => [
                'mary',
                'blessed virgin',
                'virgin mary',
                'mother of god',
                'marian',
                'rosary devotion',
                'immaculate conception',
                'assumption',
                'hail mary',
                'magnificat',
                'marian apparition',
                'our lady',
                'devotion to mary',
            ],
            'references' => [
                'Luke 1:28',
                'Luke 1:46-55',
                'John 19:26-27',
                'Genesis 3:15',
                'Revelation 12:1',
                'Luke 1:48',
            ],
            'guidance' => [
                'Mary, full of grace, cooperated uniquely in the mystery of the Incarnation and stands as Mother of the Church.',
                'Devotion to Mary leads always to her Son; imitate her faith, humility, and fiat before the word of God.',
            ],
        ],

        'separation_church_state' => [
            'keywords' => [
                'separation of church and state',
                'church and state',
                'secular state',
                'religious establishment',
                'state religion',
                'theocracy',
                'caesar and god',
                'political use of religion',
                'church involved in politics',
                'religion in government',
            ],
            'references' => [
                'Matthew 22:21',
                'John 18:36',
                'Romans 13:1-7',
                'Acts 5:29',
                'Mark 12:17',
                '1 Timothy 2:1-2',
            ],
            'guidance' => [
                'Christ distinguished earthly and spiritual authority; the Church proposes truth to society without becoming a partisan instrument of the state.',
                'Catholics may engage politics morally, but the Church\'s mission is salvation and the formation of conscience, not the seizure of worldly power.',
            ],
        ],
    ],

];
